### ISSUE TITLE
Glide code is failing 

### ISSUE THREAD

**Issue by man13sh** [PacktPublishing/How-to-Build-Android-Apps-with-Kotlin#43]
Hi I have followed 
Can you please guide how to  solve this issue? for https://github.com/PacktPublishing/How-to-Build-Android-Apps-with-Kotlin/tree/master/Chapter05/Exercise5.03

When I try to execute the code it does not show the image , in logcate I get this error as shown below:

com.example.catagentprofile W/Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored

Thanks for any help.

**Comment by EranBoudjnah** [comment]
Hi @man13sh - the above warning can safely be ignored.

I just checked out the project in Android Studio 4.2.1 and it runs correctly.

Maybe your device isn't connected to the internet? Try launching Chrome and see if you have an internet connection. Otherwise, keep looking in logcat for other warnings/errors.

**Comment by man13sh** [comment]
Thanks for the quick reply @EranBoudjnah 

I have connected to my mobile and I have internet connection and able to fetch the api data via retrofit.
Warning are ignored - but the image does not display only what I can see is the image url.

I  also have  Android Studio 4.2.1

Do the above error does not effect any part of the code?

**Comment by EranBoudjnah** [comment]
No worries!

When you say you can see the image URL - where can you see it? In exercise 5.03 you shouldn't see the image URL at all.

The above error is not a problem. I see it in my logs and images load without a problem. What Android version is your mobile running?

**Comment by man13sh** [comment]
sorry for bothering you - I just imported the code and tested it is working - I guess I have some typo somewhere in code. need to check it thoroughly.

**Comment by EranBoudjnah** [comment]
Resolved.
